apiVersion: apps/v1

kind: Deployment

metadata:

  name: jupyterspark-notebook

  labels:

    app: jupyterspark-notebook

spec:

  replicas: 1

  selector:

    matchLabels:

      app: jupyterspark-notebook

  template:

    metadata:

      labels:

        app: jupyterspark-notebook

    spec:

      containers:

      - name: spark-notebook

        image: akasharvind/jupiter

---

kind: Service

apiVersion: v1

metadata:

  name: jupyterspark-notebook

spec:

  type: NodePort

  selector:

    app: jupyterspark-notebook

  ports:

  - protocol: TCP

    nodePort: 30070

    port: 8888

    targetPort: 8888
